/* Auto-generated by emoji-generate.py, do not edit! */

/* Source file version: 17.0 */

/*
 * The code here cannot tell if a certain string is a complete valid emoji sequence, we're not interested in that.
 * It tells whether a certain string is a (possibly complete) prefix of a valid emoji sequence.
 *
 * Starting at node 0 for the first character of a string, each node tells which next node to jump to based on the next character.
 * If during lookup a NULL is encountered then it's not an emoji prefix.
 *
 * The functions' return type is the same as the functions' type (recursion, yay!), hence the necessary (void *) castings.
 */

/* Forward declarations */
static void *emoji_lookup_node_0 (gunichar c);
static void *emoji_lookup_node_1 (gunichar c);
static void *emoji_lookup_node_2 (gunichar c);
static void *emoji_lookup_node_3 (gunichar c);
static void *emoji_lookup_node_4 (gunichar c);
static void *emoji_lookup_node_5 (gunichar c);
static void *emoji_lookup_node_6 (gunichar c);
static void *emoji_lookup_node_7 (gunichar c);
static void *emoji_lookup_node_8 (gunichar c);
static void *emoji_lookup_node_9 (gunichar c);
static void *emoji_lookup_node_10 (gunichar c);
static void *emoji_lookup_node_11 (gunichar c);
static void *emoji_lookup_node_12 (gunichar c);
static void *emoji_lookup_node_13 (gunichar c);
static void *emoji_lookup_node_14 (gunichar c);
static void *emoji_lookup_node_15 (gunichar c);
static void *emoji_lookup_node_16 (gunichar c);
static void *emoji_lookup_node_17 (gunichar c);
static void *emoji_lookup_node_18 (gunichar c);
static void *emoji_lookup_node_19 (gunichar c);
static void *emoji_lookup_node_20 (gunichar c);
static void *emoji_lookup_node_21 (gunichar c);
static void *emoji_lookup_node_22 (gunichar c);
static void *emoji_lookup_node_23 (gunichar c);
static void *emoji_lookup_node_24 (gunichar c);
static void *emoji_lookup_node_25 (gunichar c);
static void *emoji_lookup_node_26 (gunichar c);
static void *emoji_lookup_node_27 (gunichar c);
static void *emoji_lookup_node_28 (gunichar c);
static void *emoji_lookup_node_29 (gunichar c);
static void *emoji_lookup_node_30 (gunichar c);
static void *emoji_lookup_node_31 (gunichar c);
static void *emoji_lookup_node_32 (gunichar c);
static void *emoji_lookup_node_33 (gunichar c);
static void *emoji_lookup_node_34 (gunichar c);
static void *emoji_lookup_node_35 (gunichar c);
static void *emoji_lookup_node_36 (gunichar c);
static void *emoji_lookup_node_37 (gunichar c);
static void *emoji_lookup_node_38 (gunichar c);
static void *emoji_lookup_node_39 (gunichar c);
static void *emoji_lookup_node_40 (gunichar c);
static void *emoji_lookup_node_41 (gunichar c);
static void *emoji_lookup_node_42 (gunichar c);
static void *emoji_lookup_node_43 (gunichar c);
static void *emoji_lookup_node_44 (gunichar c);
static void *emoji_lookup_node_45 (gunichar c);
static void *emoji_lookup_node_46 (gunichar c);
static void *emoji_lookup_node_47 (gunichar c);
static void *emoji_lookup_node_48 (gunichar c);
static void *emoji_lookup_node_49 (gunichar c);
static void *emoji_lookup_node_50 (gunichar c);
static void *emoji_lookup_node_51 (gunichar c);
static void *emoji_lookup_node_52 (gunichar c);
static void *emoji_lookup_node_53 (gunichar c);
static void *emoji_lookup_node_54 (gunichar c);
static void *emoji_lookup_node_55 (gunichar c);
static void *emoji_lookup_node_56 (gunichar c);
static void *emoji_lookup_node_57 (gunichar c);
static void *emoji_lookup_node_58 (gunichar c);
static void *emoji_lookup_node_59 (gunichar c);
static void *emoji_lookup_node_60 (gunichar c);
static void *emoji_lookup_node_61 (gunichar c);
static void *emoji_lookup_node_62 (gunichar c);
static void *emoji_lookup_node_63 (gunichar c);
static void *emoji_lookup_node_64 (gunichar c);
static void *emoji_lookup_node_65 (gunichar c);
static void *emoji_lookup_node_66 (gunichar c);
static void *emoji_lookup_node_67 (gunichar c);
static void *emoji_lookup_node_68 (gunichar c);
static void *emoji_lookup_node_69 (gunichar c);
static void *emoji_lookup_node_70 (gunichar c);
static void *emoji_lookup_node_71 (gunichar c);
static void *emoji_lookup_node_72 (gunichar c);
static void *emoji_lookup_node_73 (gunichar c);
static void *emoji_lookup_node_74 (gunichar c);
static void *emoji_lookup_node_75 (gunichar c);
static void *emoji_lookup_node_76 (gunichar c);
static void *emoji_lookup_node_77 (gunichar c);
static void *emoji_lookup_node_78 (gunichar c);
static void *emoji_lookup_node_79 (gunichar c);
static void *emoji_lookup_node_80 (gunichar c);
static void *emoji_lookup_node_81 (gunichar c);
static void *emoji_lookup_node_82 (gunichar c);
static void *emoji_lookup_node_83 (gunichar c);
static void *emoji_lookup_node_84 (gunichar c);
static void *emoji_lookup_node_85 (gunichar c);
static void *emoji_lookup_node_86 (gunichar c);
static void *emoji_lookup_node_87 (gunichar c);
static void *emoji_lookup_node_88 (gunichar c);
static void *emoji_lookup_node_89 (gunichar c);
static void *emoji_lookup_node_90 (gunichar c);
static void *emoji_lookup_node_91 (gunichar c);
static void *emoji_lookup_node_92 (gunichar c);
static void *emoji_lookup_node_93 (gunichar c);
static void *emoji_lookup_node_94 (gunichar c);
static void *emoji_lookup_node_95 (gunichar c);
static void *emoji_lookup_node_96 (gunichar c);
static void *emoji_lookup_node_97 (gunichar c);
static void *emoji_lookup_node_98 (gunichar c);
static void *emoji_lookup_node_99 (gunichar c);
static void *emoji_lookup_node_100 (gunichar c);
static void *emoji_lookup_node_101 (gunichar c);
static void *emoji_lookup_node_102 (gunichar c);
static void *emoji_lookup_node_103 (gunichar c);
static void *emoji_lookup_node_104 (gunichar c);
static void *emoji_lookup_node_105 (gunichar c);
static void *emoji_lookup_node_106 (gunichar c);
static void *emoji_lookup_node_107 (gunichar c);
static void *emoji_lookup_node_108 (gunichar c);
static void *emoji_lookup_node_109 (gunichar c);
static void *emoji_lookup_node_110 (gunichar c);
static void *emoji_lookup_node_111 (gunichar c);
static void *emoji_lookup_node_112 (gunichar c);
static void *emoji_lookup_node_113 (gunichar c);
static void *emoji_lookup_node_114 (gunichar c);
static void *emoji_lookup_node_115 (gunichar c);
static void *emoji_lookup_node_116 (gunichar c);
static void *emoji_lookup_node_117 (gunichar c);
static void *emoji_lookup_node_118 (gunichar c);
static void *emoji_lookup_node_119 (gunichar c);
static void *emoji_lookup_node_120 (gunichar c);
static void *emoji_lookup_node_121 (gunichar c);
static void *emoji_lookup_node_122 (gunichar c);
static void *emoji_lookup_node_123 (gunichar c);
static void *emoji_lookup_node_124 (gunichar c);
static void *emoji_lookup_node_125 (gunichar c);
static void *emoji_lookup_node_126 (gunichar c);
static void *emoji_lookup_node_127 (gunichar c);
static void *emoji_lookup_node_128 (gunichar c);
static void *emoji_lookup_node_129 (gunichar c);
static void *emoji_lookup_node_130 (gunichar c);
static void *emoji_lookup_node_131 (gunichar c);
static void *emoji_lookup_node_132 (gunichar c);
static void *emoji_lookup_node_133 (gunichar c);
static void *emoji_lookup_node_134 (gunichar c);
static void *emoji_lookup_node_135 (gunichar c);
static void *emoji_lookup_node_136 (gunichar c);
static void *emoji_lookup_node_137 (gunichar c);
static void *emoji_lookup_node_138 (gunichar c);
static void *emoji_lookup_node_139 (gunichar c);
static void *emoji_lookup_node_140 (gunichar c);
static void *emoji_lookup_node_141 (gunichar c);
static void *emoji_lookup_node_142 (gunichar c);
static void *emoji_lookup_node_143 (gunichar c);
static void *emoji_lookup_node_144 (gunichar c);
static void *emoji_lookup_node_145 (gunichar c);
static void *emoji_lookup_node_146 (gunichar c);
static void *emoji_lookup_node_147 (gunichar c);
static void *emoji_lookup_node_148 (gunichar c);
static void *emoji_lookup_node_149 (gunichar c);
static void *emoji_lookup_node_150 (gunichar c);
static void *emoji_lookup_node_151 (gunichar c);
static void *emoji_lookup_node_152 (gunichar c);
static void *emoji_lookup_node_153 (gunichar c);
static void *emoji_lookup_node_154 (gunichar c);
static void *emoji_lookup_node_155 (gunichar c);
static void *emoji_lookup_node_156 (gunichar c);
static void *emoji_lookup_node_157 (gunichar c);
static void *emoji_lookup_node_158 (gunichar c);
static void *emoji_lookup_node_159 (gunichar c);
static void *emoji_lookup_node_160 (gunichar c);
static void *emoji_lookup_node_161 (gunichar c);
static void *emoji_lookup_node_162 (gunichar c);
static void *emoji_lookup_node_163 (gunichar c);
static void *emoji_lookup_node_164 (gunichar c);
static void *emoji_lookup_node_165 (gunichar c);
static void *emoji_lookup_node_166 (gunichar c);
static void *emoji_lookup_node_167 (gunichar c);
static void *emoji_lookup_node_168 (gunichar c);
static void *emoji_lookup_node_169 (gunichar c);
static void *emoji_lookup_node_170 (gunichar c);
static void *emoji_lookup_node_171 (gunichar c);
static void *emoji_lookup_node_172 (gunichar c);
static void *emoji_lookup_node_173 (gunichar c);
static void *emoji_lookup_node_174 (gunichar c);
static void *emoji_lookup_node_175 (gunichar c);
static void *emoji_lookup_node_176 (gunichar c);
static void *emoji_lookup_node_177 (gunichar c);
static void *emoji_lookup_node_178 (gunichar c);
static void *emoji_lookup_node_179 (gunichar c);
static void *emoji_lookup_node_180 (gunichar c);
static void *emoji_lookup_node_181 (gunichar c);
static void *emoji_lookup_node_182 (gunichar c);
static void *emoji_lookup_node_183 (gunichar c);
static void *emoji_lookup_node_184 (gunichar c);
static void *emoji_lookup_node_185 (gunichar c);
static void *emoji_lookup_node_186 (gunichar c);
static void *emoji_lookup_node_187 (gunichar c);
static void *emoji_lookup_node_188 (gunichar c);
static void *emoji_lookup_node_189 (gunichar c);
static void *emoji_lookup_node_190 (gunichar c);
static void *emoji_lookup_node_191 (gunichar c);
static void *emoji_lookup_node_192 (gunichar c);

/* Jump tables
 *
 * Note that gcc/clang-optimized switch() seems to be significantly faster
 * than binary searching in predefined arrays. */

static void *emoji_lookup_node_0 (gunichar c)
{
  switch (c) {
  case 0x00A9:
  case 0x00AE:
  case 0x203C:
  case 0x2049:
  case 0x2122:
  case 0x2139:
  case 0x2194 ... 0x2199 /* 6 */:
  case 0x21A9 ... 0x21AA /* 2 */:
  case 0x2328:
  case 0x23CF:
  case 0x23ED ... 0x23EF /* 3 */:
  case 0x23F1 ... 0x23F2 /* 2 */:
  case 0x23F8 ... 0x23FA /* 3 */:
  case 0x24C2:
  case 0x25AA ... 0x25AB /* 2 */:
  case 0x25B6:
  case 0x25C0:
  case 0x25FB ... 0x25FC /* 2 */:
  case 0x2600 ... 0x2604 /* 5 */:
  case 0x260E:
  case 0x2611:
  case 0x2618:
  case 0x2620:
  case 0x2622 ... 0x2623 /* 2 */:
  case 0x2626:
  case 0x262A:
  case 0x262E ... 0x262F /* 2 */:
  case 0x2638 ... 0x263A /* 3 */:
  case 0x2640:
  case 0x2642:
  case 0x265F ... 0x2660 /* 2 */:
  case 0x2663:
  case 0x2665 ... 0x2666 /* 2 */:
  case 0x2668:
  case 0x267B:
  case 0x267E:
  case 0x2692:
  case 0x2694 ... 0x2697 /* 4 */:
  case 0x2699:
  case 0x269B ... 0x269C /* 2 */:
  case 0x26A0:
  case 0x26A7:
  case 0x26B0 ... 0x26B1 /* 2 */:
  case 0x26C8:
  case 0x26CF:
  case 0x26D1:
  case 0x26E9:
  case 0x26F0 ... 0x26F1 /* 2 */:
  case 0x26F4:
  case 0x26F7 ... 0x26F8 /* 2 */:
  case 0x2702:
  case 0x2708 ... 0x2709 /* 2 */:
  case 0x270F:
  case 0x2712:
  case 0x2714:
  case 0x2716:
  case 0x271D:
  case 0x2721:
  case 0x2733 ... 0x2734 /* 2 */:
  case 0x2744:
  case 0x2747:
  case 0x2763:
  case 0x27A1:
  case 0x2934 ... 0x2935 /* 2 */:
  case 0x2B05 ... 0x2B07 /* 3 */:
  case 0x3030:
  case 0x303D:
  case 0x3297:
  case 0x3299:
  case 0x1F170 ... 0x1F171 /* 2 */:
  case 0x1F17E ... 0x1F17F /* 2 */:
  case 0x1F202:
  case 0x1F237:
  case 0x1F321:
  case 0x1F324 ... 0x1F32C /* 9 */:
  case 0x1F336:
  case 0x1F37D:
  case 0x1F396 ... 0x1F397 /* 2 */:
  case 0x1F399 ... 0x1F39B /* 3 */:
  case 0x1F39E ... 0x1F39F /* 2 */:
  case 0x1F3CD ... 0x1F3CE /* 2 */:
  case 0x1F3D4 ... 0x1F3DF /* 12 */:
  case 0x1F3F5:
  case 0x1F3F7:
  case 0x1F43F:
  case 0x1F4FD:
  case 0x1F549 ... 0x1F54A /* 2 */:
  case 0x1F56F ... 0x1F570 /* 2 */:
  case 0x1F573:
  case 0x1F576 ... 0x1F579 /* 4 */:
  case 0x1F587:
  case 0x1F58A ... 0x1F58D /* 4 */:
  case 0x1F5A5:
  case 0x1F5A8:
  case 0x1F5B1 ... 0x1F5B2 /* 2 */:
  case 0x1F5BC:
  case 0x1F5C2 ... 0x1F5C4 /* 3 */:
  case 0x1F5D1 ... 0x1F5D3 /* 3 */:
  case 0x1F5DC ... 0x1F5DE /* 3 */:
  case 0x1F5E1:
  case 0x1F5E3:
  case 0x1F5E8:
  case 0x1F5EF:
  case 0x1F5F3:
  case 0x1F5FA:
  case 0x1F6CB:
  case 0x1F6CD ... 0x1F6CF /* 3 */:
  case 0x1F6E0 ... 0x1F6E5 /* 6 */:
  case 0x1F6E9:
  case 0x1F6F0:
  case 0x1F6F3:
    return (void *) emoji_lookup_node_1;
  case 0x1F636:
    return (void *) emoji_lookup_node_3;
  case 0x1F62E:
    return (void *) emoji_lookup_node_5;
  case 0x1F642:
    return (void *) emoji_lookup_node_7;
  case 0x1F635:
    return (void *) emoji_lookup_node_9;
  case 0x2764:
    return (void *) emoji_lookup_node_11;
  case 0x1F441:
    return (void *) emoji_lookup_node_14;
  case 0x270A ... 0x270B /* 2 */:
  case 0x1F385:
  case 0x1F3C2:
  case 0x1F3C7:
  case 0x1F442 ... 0x1F443 /* 2 */:
  case 0x1F446 ... 0x1F450 /* 11 */:
  case 0x1F466 ... 0x1F467 /* 2 */:
  case 0x1F46B ... 0x1F46D /* 3 */:
  case 0x1F472:
  case 0x1F474 ... 0x1F476 /* 3 */:
  case 0x1F478:
  case 0x1F47C:
  case 0x1F483:
  case 0x1F485:
  case 0x1F48F:
  case 0x1F491:
  case 0x1F4AA:
  case 0x1F57A:
  case 0x1F595 ... 0x1F596 /* 2 */:
  case 0x1F64C:
  case 0x1F64F:
  case 0x1F6C0:
  case 0x1F6CC:
  case 0x1F90C:
  case 0x1F90F:
  case 0x1F918 ... 0x1F91F /* 8 */:
  case 0x1F930 ... 0x1F934 /* 5 */:
  case 0x1F936:
  case 0x1F977:
  case 0x1F9B5 ... 0x1F9B6 /* 2 */:
  case 0x1F9BB:
  case 0x1F9D2 ... 0x1F9D3 /* 2 */:
  case 0x1F9D5:
  case 0x1FAC3 ... 0x1FAC5 /* 3 */:
  case 0x1FAF0:
  case 0x1FAF2 ... 0x1FAF8 /* 7 */:
    return (void *) emoji_lookup_node_17;
  case 0x261D:
  case 0x270C ... 0x270D /* 2 */:
  case 0x1F574:
  case 0x1F590:
    return (void *) emoji_lookup_node_18;
  case 0x1FAF1:
    return (void *) emoji_lookup_node_19;
  case 0x1F9D1:
    return (void *) emoji_lookup_node_35;
  case 0x1F3C4:
  case 0x1F3CA:
  case 0x1F46E ... 0x1F471 /* 4 */:
  case 0x1F473:
  case 0x1F477:
  case 0x1F481 ... 0x1F482 /* 2 */:
  case 0x1F486 ... 0x1F487 /* 2 */:
  case 0x1F645 ... 0x1F647 /* 3 */:
  case 0x1F64B:
  case 0x1F64D ... 0x1F64E /* 2 */:
  case 0x1F6A3:
  case 0x1F6B4 ... 0x1F6B5 /* 2 */:
  case 0x1F926:
  case 0x1F935:
  case 0x1F937 ... 0x1F939 /* 3 */:
  case 0x1F93C ... 0x1F93E /* 3 */:
  case 0x1F9B8 ... 0x1F9B9 /* 2 */:
  case 0x1F9CD:
  case 0x1F9CF:
  case 0x1F9D4:
  case 0x1F9D6 ... 0x1F9DD /* 8 */:
    return (void *) emoji_lookup_node_41;
  case 0x1F468:
    return (void *) emoji_lookup_node_43;
  case 0x1F469:
    return (void *) emoji_lookup_node_56;
  case 0x26F9:
  case 0x1F3CB ... 0x1F3CC /* 2 */:
  case 0x1F575:
    return (void *) emoji_lookup_node_74;
  case 0x1F9DE ... 0x1F9DF /* 2 */:
    return (void *) emoji_lookup_node_42;
  case 0x1F3C3:
  case 0x1F6B6:
  case 0x1F9CE:
    return (void *) emoji_lookup_node_75;
  case 0x1F415:
    return (void *) emoji_lookup_node_170;
  case 0x1F408:
    return (void *) emoji_lookup_node_172;
  case 0x1F43B:
    return (void *) emoji_lookup_node_174;
  case 0x1F426:
    return (void *) emoji_lookup_node_176;
  case 0x1F34B:
    return (void *) emoji_lookup_node_178;
  case 0x1F344:
    return (void *) emoji_lookup_node_180;
  case 0x26D3:
    return (void *) emoji_lookup_node_182;
  case 0x0023:
  case 0x002A:
  case 0x0030 ... 0x0039 /* 10 */:
    return (void *) emoji_lookup_node_185;
  case 0x1F3F3:
    return (void *) emoji_lookup_node_187;
  case 0x1F3F4:
    return (void *) emoji_lookup_node_190;
  case 0x1F1E6 ... 0x1F1FF /* 26 */:
    return (void *) emoji_lookup_node_192;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_1 (gunichar c)
{
  switch (c) {
  case 0xFE0F:
    return (void *) emoji_lookup_node_2;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_2 (gunichar c)
{
  switch (c) {
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_3 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_4;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_4 (gunichar c)
{
  switch (c) {
  case 0x1F32B:
    return (void *) emoji_lookup_node_1;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_5 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_6;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_6 (gunichar c)
{
  switch (c) {
  case 0x1F4A8:
    return (void *) emoji_lookup_node_2;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_7 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_8;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_8 (gunichar c)
{
  switch (c) {
  case 0x2194 ... 0x2195 /* 2 */:
    return (void *) emoji_lookup_node_1;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_9 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_10;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_10 (gunichar c)
{
  switch (c) {
  case 0x1F4AB:
    return (void *) emoji_lookup_node_2;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_11 (gunichar c)
{
  switch (c) {
  case 0xFE0F:
    return (void *) emoji_lookup_node_12;
  case 0x200D:
    return (void *) emoji_lookup_node_13;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_12 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_13;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_13 (gunichar c)
{
  switch (c) {
  case 0x1F525:
  case 0x1FA79:
    return (void *) emoji_lookup_node_2;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_14 (gunichar c)
{
  switch (c) {
  case 0xFE0F:
    return (void *) emoji_lookup_node_15;
  case 0x200D:
    return (void *) emoji_lookup_node_16;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_15 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_16;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_16 (gunichar c)
{
  switch (c) {
  case 0x1F5E8:
    return (void *) emoji_lookup_node_1;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_17 (gunichar c)
{
  switch (c) {
  case 0x1F3FB ... 0x1F3FF /* 5 */:
    return (void *) emoji_lookup_node_2;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_18 (gunichar c)
{
  switch (c) {
  case 0xFE0F:
  case 0x1F3FB ... 0x1F3FF /* 5 */:
    return (void *) emoji_lookup_node_2;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_19 (gunichar c)
{
  switch (c) {
  case 0x1F3FB:
    return (void *) emoji_lookup_node_20;
  case 0x1F3FC:
    return (void *) emoji_lookup_node_21;
  case 0x1F3FD:
    return (void *) emoji_lookup_node_22;
  case 0x1F3FE:
    return (void *) emoji_lookup_node_23;
  case 0x1F3FF:
    return (void *) emoji_lookup_node_24;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_20 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_25;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_21 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_27;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_22 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_29;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_23 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_31;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_24 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_33;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_25 (gunichar c)
{
  switch (c) {
  case 0x1FAF2:
    return (void *) emoji_lookup_node_26;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_26 (gunichar c)
{
  switch (c) {
  case 0x1F3FC ... 0x1F3FF /* 4 */:
    return (void *) emoji_lookup_node_2;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_27 (gunichar c)
{
  switch (c) {
  case 0x1FAF2:
    return (void *) emoji_lookup_node_28;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_28 (gunichar c)
{
  switch (c) {
  case 0x1F3FB:
  case 0x1F3FD ... 0x1F3FF /* 3 */:
    return (void *) emoji_lookup_node_2;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_29 (gunichar c)
{
  switch (c) {
  case 0x1FAF2:
    return (void *) emoji_lookup_node_30;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_30 (gunichar c)
{
  switch (c) {
  case 0x1F3FB ... 0x1F3FC /* 2 */:
  case 0x1F3FE ... 0x1F3FF /* 2 */:
    return (void *) emoji_lookup_node_2;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_31 (gunichar c)
{
  switch (c) {
  case 0x1FAF2:
    return (void *) emoji_lookup_node_32;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_32 (gunichar c)
{
  switch (c) {
  case 0x1F3FB ... 0x1F3FD /* 3 */:
  case 0x1F3FF:
    return (void *) emoji_lookup_node_2;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_33 (gunichar c)
{
  switch (c) {
  case 0x1FAF2:
    return (void *) emoji_lookup_node_34;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_34 (gunichar c)
{
  switch (c) {
  case 0x1F3FB ... 0x1F3FE /* 4 */:
    return (void *) emoji_lookup_node_2;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_35 (gunichar c)
{
  switch (c) {
  case 0x1F3FB:
    return (void *) emoji_lookup_node_36;
  case 0x1F3FC:
    return (void *) emoji_lookup_node_37;
  case 0x1F3FD:
    return (void *) emoji_lookup_node_38;
  case 0x1F3FE:
    return (void *) emoji_lookup_node_39;
  case 0x1F3FF:
    return (void *) emoji_lookup_node_40;
  case 0x200D:
    return (void *) emoji_lookup_node_68;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_36 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_69;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_37 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_70;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_38 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_71;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_39 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_72;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_40 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_73;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_41 (gunichar c)
{
  switch (c) {
  case 0x1F3FB ... 0x1F3FF /* 5 */:
    return (void *) emoji_lookup_node_42;
  case 0x200D:
    return (void *) emoji_lookup_node_49;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_42 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_49;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_43 (gunichar c)
{
  switch (c) {
  case 0x1F3FB:
    return (void *) emoji_lookup_node_44;
  case 0x1F3FC:
    return (void *) emoji_lookup_node_45;
  case 0x1F3FD:
    return (void *) emoji_lookup_node_46;
  case 0x1F3FE:
    return (void *) emoji_lookup_node_47;
  case 0x1F3FF:
    return (void *) emoji_lookup_node_48;
  case 0x200D:
    return (void *) emoji_lookup_node_50;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_44 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_51;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_45 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_52;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_46 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_53;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_47 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_54;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_48 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_55;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_49 (gunichar c)
{
  switch (c) {
  case 0x2640:
  case 0x2642:
    return (void *) emoji_lookup_node_1;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_50 (gunichar c)
{
  switch (c) {
  case 0x1F33E:
  case 0x1F373:
  case 0x1F37C:
  case 0x1F393:
  case 0x1F3A4:
  case 0x1F3A8:
  case 0x1F3EB:
  case 0x1F3ED:
  case 0x1F4BB ... 0x1F4BC /* 2 */:
  case 0x1F527:
  case 0x1F52C:
  case 0x1F680:
  case 0x1F692:
  case 0x1F9B0 ... 0x1F9B3 /* 4 */:
    return (void *) emoji_lookup_node_2;
  case 0x2695 ... 0x2696 /* 2 */:
  case 0x2708:
    return (void *) emoji_lookup_node_1;
  case 0x1F9AF:
  case 0x1F9BC ... 0x1F9BD /* 2 */:
    return (void *) emoji_lookup_node_79;
  case 0x2764:
    return (void *) emoji_lookup_node_150;
  case 0x1F468 ... 0x1F469 /* 2 */:
    return (void *) emoji_lookup_node_160;
  case 0x1F466:
    return (void *) emoji_lookup_node_162;
  case 0x1F467:
    return (void *) emoji_lookup_node_163;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_51 (gunichar c)
{
  switch (c) {
  case 0x1F33E:
  case 0x1F373:
  case 0x1F37C:
  case 0x1F393:
  case 0x1F3A4:
  case 0x1F3A8:
  case 0x1F3EB:
  case 0x1F3ED:
  case 0x1F4BB ... 0x1F4BC /* 2 */:
  case 0x1F527:
  case 0x1F52C:
  case 0x1F680:
  case 0x1F692:
  case 0x1F9B0 ... 0x1F9B3 /* 4 */:
    return (void *) emoji_lookup_node_2;
  case 0x2695 ... 0x2696 /* 2 */:
  case 0x2708:
    return (void *) emoji_lookup_node_1;
  case 0x1F9AF:
  case 0x1F9BC ... 0x1F9BD /* 2 */:
    return (void *) emoji_lookup_node_79;
  case 0x1F430:
  case 0x1F91D:
  case 0x1FAEF:
    return (void *) emoji_lookup_node_91;
  case 0x2764:
    return (void *) emoji_lookup_node_155;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_52 (gunichar c)
{
  switch (c) {
  case 0x1F33E:
  case 0x1F373:
  case 0x1F37C:
  case 0x1F393:
  case 0x1F3A4:
  case 0x1F3A8:
  case 0x1F3EB:
  case 0x1F3ED:
  case 0x1F4BB ... 0x1F4BC /* 2 */:
  case 0x1F527:
  case 0x1F52C:
  case 0x1F680:
  case 0x1F692:
  case 0x1F9B0 ... 0x1F9B3 /* 4 */:
    return (void *) emoji_lookup_node_2;
  case 0x2695 ... 0x2696 /* 2 */:
  case 0x2708:
    return (void *) emoji_lookup_node_1;
  case 0x1F9AF:
  case 0x1F9BC ... 0x1F9BD /* 2 */:
    return (void *) emoji_lookup_node_79;
  case 0x1F430:
  case 0x1F91D:
  case 0x1FAEF:
    return (void *) emoji_lookup_node_93;
  case 0x2764:
    return (void *) emoji_lookup_node_155;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_53 (gunichar c)
{
  switch (c) {
  case 0x1F33E:
  case 0x1F373:
  case 0x1F37C:
  case 0x1F393:
  case 0x1F3A4:
  case 0x1F3A8:
  case 0x1F3EB:
  case 0x1F3ED:
  case 0x1F4BB ... 0x1F4BC /* 2 */:
  case 0x1F527:
  case 0x1F52C:
  case 0x1F680:
  case 0x1F692:
  case 0x1F9B0 ... 0x1F9B3 /* 4 */:
    return (void *) emoji_lookup_node_2;
  case 0x2695 ... 0x2696 /* 2 */:
  case 0x2708:
    return (void *) emoji_lookup_node_1;
  case 0x1F9AF:
  case 0x1F9BC ... 0x1F9BD /* 2 */:
    return (void *) emoji_lookup_node_79;
  case 0x1F430:
  case 0x1F91D:
  case 0x1FAEF:
    return (void *) emoji_lookup_node_95;
  case 0x2764:
    return (void *) emoji_lookup_node_155;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_54 (gunichar c)
{
  switch (c) {
  case 0x1F33E:
  case 0x1F373:
  case 0x1F37C:
  case 0x1F393:
  case 0x1F3A4:
  case 0x1F3A8:
  case 0x1F3EB:
  case 0x1F3ED:
  case 0x1F4BB ... 0x1F4BC /* 2 */:
  case 0x1F527:
  case 0x1F52C:
  case 0x1F680:
  case 0x1F692:
  case 0x1F9B0 ... 0x1F9B3 /* 4 */:
    return (void *) emoji_lookup_node_2;
  case 0x2695 ... 0x2696 /* 2 */:
  case 0x2708:
    return (void *) emoji_lookup_node_1;
  case 0x1F9AF:
  case 0x1F9BC ... 0x1F9BD /* 2 */:
    return (void *) emoji_lookup_node_79;
  case 0x1F430:
  case 0x1F91D:
  case 0x1FAEF:
    return (void *) emoji_lookup_node_97;
  case 0x2764:
    return (void *) emoji_lookup_node_155;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_55 (gunichar c)
{
  switch (c) {
  case 0x1F33E:
  case 0x1F373:
  case 0x1F37C:
  case 0x1F393:
  case 0x1F3A4:
  case 0x1F3A8:
  case 0x1F3EB:
  case 0x1F3ED:
  case 0x1F4BB ... 0x1F4BC /* 2 */:
  case 0x1F527:
  case 0x1F52C:
  case 0x1F680:
  case 0x1F692:
  case 0x1F9B0 ... 0x1F9B3 /* 4 */:
    return (void *) emoji_lookup_node_2;
  case 0x2695 ... 0x2696 /* 2 */:
  case 0x2708:
    return (void *) emoji_lookup_node_1;
  case 0x1F9AF:
  case 0x1F9BC ... 0x1F9BD /* 2 */:
    return (void *) emoji_lookup_node_79;
  case 0x1F430:
  case 0x1F91D:
  case 0x1FAEF:
    return (void *) emoji_lookup_node_99;
  case 0x2764:
    return (void *) emoji_lookup_node_155;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_56 (gunichar c)
{
  switch (c) {
  case 0x1F3FB:
    return (void *) emoji_lookup_node_57;
  case 0x1F3FC:
    return (void *) emoji_lookup_node_58;
  case 0x1F3FD:
    return (void *) emoji_lookup_node_59;
  case 0x1F3FE:
    return (void *) emoji_lookup_node_60;
  case 0x1F3FF:
    return (void *) emoji_lookup_node_61;
  case 0x200D:
    return (void *) emoji_lookup_node_62;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_57 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_63;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_58 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_64;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_59 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_65;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_60 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_66;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_61 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_67;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_62 (gunichar c)
{
  switch (c) {
  case 0x1F33E:
  case 0x1F373:
  case 0x1F37C:
  case 0x1F393:
  case 0x1F3A4:
  case 0x1F3A8:
  case 0x1F3EB:
  case 0x1F3ED:
  case 0x1F4BB ... 0x1F4BC /* 2 */:
  case 0x1F527:
  case 0x1F52C:
  case 0x1F680:
  case 0x1F692:
  case 0x1F9B0 ... 0x1F9B3 /* 4 */:
    return (void *) emoji_lookup_node_2;
  case 0x2695 ... 0x2696 /* 2 */:
  case 0x2708:
    return (void *) emoji_lookup_node_1;
  case 0x1F9AF:
  case 0x1F9BC ... 0x1F9BD /* 2 */:
    return (void *) emoji_lookup_node_79;
  case 0x2764:
    return (void *) emoji_lookup_node_140;
  case 0x1F469:
    return (void *) emoji_lookup_node_160;
  case 0x1F466:
    return (void *) emoji_lookup_node_162;
  case 0x1F467:
    return (void *) emoji_lookup_node_163;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_63 (gunichar c)
{
  switch (c) {
  case 0x1F33E:
  case 0x1F373:
  case 0x1F37C:
  case 0x1F393:
  case 0x1F3A4:
  case 0x1F3A8:
  case 0x1F3EB:
  case 0x1F3ED:
  case 0x1F4BB ... 0x1F4BC /* 2 */:
  case 0x1F527:
  case 0x1F52C:
  case 0x1F680:
  case 0x1F692:
  case 0x1F9B0 ... 0x1F9B3 /* 4 */:
    return (void *) emoji_lookup_node_2;
  case 0x2695 ... 0x2696 /* 2 */:
  case 0x2708:
    return (void *) emoji_lookup_node_1;
  case 0x1F9AF:
  case 0x1F9BC ... 0x1F9BD /* 2 */:
    return (void *) emoji_lookup_node_79;
  case 0x1F430:
  case 0x1FAEF:
    return (void *) emoji_lookup_node_101;
  case 0x1F91D:
    return (void *) emoji_lookup_node_115;
  case 0x2764:
    return (void *) emoji_lookup_node_145;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_64 (gunichar c)
{
  switch (c) {
  case 0x1F33E:
  case 0x1F373:
  case 0x1F37C:
  case 0x1F393:
  case 0x1F3A4:
  case 0x1F3A8:
  case 0x1F3EB:
  case 0x1F3ED:
  case 0x1F4BB ... 0x1F4BC /* 2 */:
  case 0x1F527:
  case 0x1F52C:
  case 0x1F680:
  case 0x1F692:
  case 0x1F9B0 ... 0x1F9B3 /* 4 */:
    return (void *) emoji_lookup_node_2;
  case 0x2695 ... 0x2696 /* 2 */:
  case 0x2708:
    return (void *) emoji_lookup_node_1;
  case 0x1F9AF:
  case 0x1F9BC ... 0x1F9BD /* 2 */:
    return (void *) emoji_lookup_node_79;
  case 0x1F430:
  case 0x1FAEF:
    return (void *) emoji_lookup_node_103;
  case 0x1F91D:
    return (void *) emoji_lookup_node_117;
  case 0x2764:
    return (void *) emoji_lookup_node_145;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_65 (gunichar c)
{
  switch (c) {
  case 0x1F33E:
  case 0x1F373:
  case 0x1F37C:
  case 0x1F393:
  case 0x1F3A4:
  case 0x1F3A8:
  case 0x1F3EB:
  case 0x1F3ED:
  case 0x1F4BB ... 0x1F4BC /* 2 */:
  case 0x1F527:
  case 0x1F52C:
  case 0x1F680:
  case 0x1F692:
  case 0x1F9B0 ... 0x1F9B3 /* 4 */:
    return (void *) emoji_lookup_node_2;
  case 0x2695 ... 0x2696 /* 2 */:
  case 0x2708:
    return (void *) emoji_lookup_node_1;
  case 0x1F9AF:
  case 0x1F9BC ... 0x1F9BD /* 2 */:
    return (void *) emoji_lookup_node_79;
  case 0x1F430:
  case 0x1FAEF:
    return (void *) emoji_lookup_node_105;
  case 0x1F91D:
    return (void *) emoji_lookup_node_119;
  case 0x2764:
    return (void *) emoji_lookup_node_145;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_66 (gunichar c)
{
  switch (c) {
  case 0x1F33E:
  case 0x1F373:
  case 0x1F37C:
  case 0x1F393:
  case 0x1F3A4:
  case 0x1F3A8:
  case 0x1F3EB:
  case 0x1F3ED:
  case 0x1F4BB ... 0x1F4BC /* 2 */:
  case 0x1F527:
  case 0x1F52C:
  case 0x1F680:
  case 0x1F692:
  case 0x1F9B0 ... 0x1F9B3 /* 4 */:
    return (void *) emoji_lookup_node_2;
  case 0x2695 ... 0x2696 /* 2 */:
  case 0x2708:
    return (void *) emoji_lookup_node_1;
  case 0x1F9AF:
  case 0x1F9BC ... 0x1F9BD /* 2 */:
    return (void *) emoji_lookup_node_79;
  case 0x1F430:
  case 0x1FAEF:
    return (void *) emoji_lookup_node_107;
  case 0x1F91D:
    return (void *) emoji_lookup_node_121;
  case 0x2764:
    return (void *) emoji_lookup_node_145;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_67 (gunichar c)
{
  switch (c) {
  case 0x1F33E:
  case 0x1F373:
  case 0x1F37C:
  case 0x1F393:
  case 0x1F3A4:
  case 0x1F3A8:
  case 0x1F3EB:
  case 0x1F3ED:
  case 0x1F4BB ... 0x1F4BC /* 2 */:
  case 0x1F527:
  case 0x1F52C:
  case 0x1F680:
  case 0x1F692:
  case 0x1F9B0 ... 0x1F9B3 /* 4 */:
    return (void *) emoji_lookup_node_2;
  case 0x2695 ... 0x2696 /* 2 */:
  case 0x2708:
    return (void *) emoji_lookup_node_1;
  case 0x1F9AF:
  case 0x1F9BC ... 0x1F9BD /* 2 */:
    return (void *) emoji_lookup_node_79;
  case 0x1F430:
  case 0x1FAEF:
    return (void *) emoji_lookup_node_109;
  case 0x1F91D:
    return (void *) emoji_lookup_node_123;
  case 0x2764:
    return (void *) emoji_lookup_node_145;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_68 (gunichar c)
{
  switch (c) {
  case 0x1F33E:
  case 0x1F373:
  case 0x1F37C:
  case 0x1F384:
  case 0x1F393:
  case 0x1F3A4:
  case 0x1F3A8:
  case 0x1F3EB:
  case 0x1F3ED:
  case 0x1F4BB ... 0x1F4BC /* 2 */:
  case 0x1F527:
  case 0x1F52C:
  case 0x1F680:
  case 0x1F692:
  case 0x1F9B0 ... 0x1F9B3 /* 4 */:
  case 0x1FA70:
    return (void *) emoji_lookup_node_2;
  case 0x2695 ... 0x2696 /* 2 */:
  case 0x2708:
    return (void *) emoji_lookup_node_1;
  case 0x1F9AF:
  case 0x1F9BC ... 0x1F9BD /* 2 */:
    return (void *) emoji_lookup_node_79;
  case 0x1F91D:
    return (void *) emoji_lookup_node_111;
  case 0x1F9D1:
    return (void *) emoji_lookup_node_166;
  case 0x1F9D2:
    return (void *) emoji_lookup_node_168;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_69 (gunichar c)
{
  switch (c) {
  case 0x1F33E:
  case 0x1F373:
  case 0x1F37C:
  case 0x1F384:
  case 0x1F393:
  case 0x1F3A4:
  case 0x1F3A8:
  case 0x1F3EB:
  case 0x1F3ED:
  case 0x1F4BB ... 0x1F4BC /* 2 */:
  case 0x1F527:
  case 0x1F52C:
  case 0x1F680:
  case 0x1F692:
  case 0x1F9B0 ... 0x1F9B3 /* 4 */:
  case 0x1FA70:
    return (void *) emoji_lookup_node_2;
  case 0x2695 ... 0x2696 /* 2 */:
  case 0x2708:
    return (void *) emoji_lookup_node_1;
  case 0x1F9AF:
  case 0x1F9BC ... 0x1F9BD /* 2 */:
    return (void *) emoji_lookup_node_79;
  case 0x1F430:
  case 0x1FAEF:
    return (void *) emoji_lookup_node_81;
  case 0x1F91D:
    return (void *) emoji_lookup_node_113;
  case 0x2764:
    return (void *) emoji_lookup_node_125;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_70 (gunichar c)
{
  switch (c) {
  case 0x1F33E:
  case 0x1F373:
  case 0x1F37C:
  case 0x1F384:
  case 0x1F393:
  case 0x1F3A4:
  case 0x1F3A8:
  case 0x1F3EB:
  case 0x1F3ED:
  case 0x1F4BB ... 0x1F4BC /* 2 */:
  case 0x1F527:
  case 0x1F52C:
  case 0x1F680:
  case 0x1F692:
  case 0x1F9B0 ... 0x1F9B3 /* 4 */:
  case 0x1FA70:
    return (void *) emoji_lookup_node_2;
  case 0x2695 ... 0x2696 /* 2 */:
  case 0x2708:
    return (void *) emoji_lookup_node_1;
  case 0x1F9AF:
  case 0x1F9BC ... 0x1F9BD /* 2 */:
    return (void *) emoji_lookup_node_79;
  case 0x1F430:
  case 0x1FAEF:
    return (void *) emoji_lookup_node_83;
  case 0x1F91D:
    return (void *) emoji_lookup_node_113;
  case 0x2764:
    return (void *) emoji_lookup_node_128;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_71 (gunichar c)
{
  switch (c) {
  case 0x1F33E:
  case 0x1F373:
  case 0x1F37C:
  case 0x1F384:
  case 0x1F393:
  case 0x1F3A4:
  case 0x1F3A8:
  case 0x1F3EB:
  case 0x1F3ED:
  case 0x1F4BB ... 0x1F4BC /* 2 */:
  case 0x1F527:
  case 0x1F52C:
  case 0x1F680:
  case 0x1F692:
  case 0x1F9B0 ... 0x1F9B3 /* 4 */:
  case 0x1FA70:
    return (void *) emoji_lookup_node_2;
  case 0x2695 ... 0x2696 /* 2 */:
  case 0x2708:
    return (void *) emoji_lookup_node_1;
  case 0x1F9AF:
  case 0x1F9BC ... 0x1F9BD /* 2 */:
    return (void *) emoji_lookup_node_79;
  case 0x1F430:
  case 0x1FAEF:
    return (void *) emoji_lookup_node_85;
  case 0x1F91D:
    return (void *) emoji_lookup_node_113;
  case 0x2764:
    return (void *) emoji_lookup_node_131;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_72 (gunichar c)
{
  switch (c) {
  case 0x1F33E:
  case 0x1F373:
  case 0x1F37C:
  case 0x1F384:
  case 0x1F393:
  case 0x1F3A4:
  case 0x1F3A8:
  case 0x1F3EB:
  case 0x1F3ED:
  case 0x1F4BB ... 0x1F4BC /* 2 */:
  case 0x1F527:
  case 0x1F52C:
  case 0x1F680:
  case 0x1F692:
  case 0x1F9B0 ... 0x1F9B3 /* 4 */:
  case 0x1FA70:
    return (void *) emoji_lookup_node_2;
  case 0x2695 ... 0x2696 /* 2 */:
  case 0x2708:
    return (void *) emoji_lookup_node_1;
  case 0x1F9AF:
  case 0x1F9BC ... 0x1F9BD /* 2 */:
    return (void *) emoji_lookup_node_79;
  case 0x1F430:
  case 0x1FAEF:
    return (void *) emoji_lookup_node_87;
  case 0x1F91D:
    return (void *) emoji_lookup_node_113;
  case 0x2764:
    return (void *) emoji_lookup_node_134;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_73 (gunichar c)
{
  switch (c) {
  case 0x1F33E:
  case 0x1F373:
  case 0x1F37C:
  case 0x1F384:
  case 0x1F393:
  case 0x1F3A4:
  case 0x1F3A8:
  case 0x1F3EB:
  case 0x1F3ED:
  case 0x1F4BB ... 0x1F4BC /* 2 */:
  case 0x1F527:
  case 0x1F52C:
  case 0x1F680:
  case 0x1F692:
  case 0x1F9B0 ... 0x1F9B3 /* 4 */:
  case 0x1FA70:
    return (void *) emoji_lookup_node_2;
  case 0x2695 ... 0x2696 /* 2 */:
  case 0x2708:
    return (void *) emoji_lookup_node_1;
  case 0x1F9AF:
  case 0x1F9BC ... 0x1F9BD /* 2 */:
    return (void *) emoji_lookup_node_79;
  case 0x1F430:
  case 0x1FAEF:
    return (void *) emoji_lookup_node_89;
  case 0x1F91D:
    return (void *) emoji_lookup_node_113;
  case 0x2764:
    return (void *) emoji_lookup_node_137;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_74 (gunichar c)
{
  switch (c) {
  case 0xFE0F:
  case 0x1F3FB ... 0x1F3FF /* 5 */:
    return (void *) emoji_lookup_node_42;
  case 0x200D:
    return (void *) emoji_lookup_node_49;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_75 (gunichar c)
{
  switch (c) {
  case 0x1F3FB ... 0x1F3FF /* 5 */:
    return (void *) emoji_lookup_node_76;
  case 0x200D:
    return (void *) emoji_lookup_node_77;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_76 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_77;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_77 (gunichar c)
{
  switch (c) {
  case 0x2640:
  case 0x2642:
    return (void *) emoji_lookup_node_78;
  case 0x27A1:
    return (void *) emoji_lookup_node_1;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_78 (gunichar c)
{
  switch (c) {
  case 0xFE0F:
    return (void *) emoji_lookup_node_79;
  case 0x200D:
    return (void *) emoji_lookup_node_80;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_79 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_80;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_80 (gunichar c)
{
  switch (c) {
  case 0x27A1:
    return (void *) emoji_lookup_node_1;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_81 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_82;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_82 (gunichar c)
{
  switch (c) {
  case 0x1F9D1:
    return (void *) emoji_lookup_node_26;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_83 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_84;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_84 (gunichar c)
{
  switch (c) {
  case 0x1F9D1:
    return (void *) emoji_lookup_node_28;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_85 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_86;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_86 (gunichar c)
{
  switch (c) {
  case 0x1F9D1:
    return (void *) emoji_lookup_node_30;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_87 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_88;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_88 (gunichar c)
{
  switch (c) {
  case 0x1F9D1:
    return (void *) emoji_lookup_node_32;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_89 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_90;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_90 (gunichar c)
{
  switch (c) {
  case 0x1F9D1:
    return (void *) emoji_lookup_node_34;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_91 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_92;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_92 (gunichar c)
{
  switch (c) {
  case 0x1F468:
    return (void *) emoji_lookup_node_26;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_93 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_94;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_94 (gunichar c)
{
  switch (c) {
  case 0x1F468:
    return (void *) emoji_lookup_node_28;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_95 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_96;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_96 (gunichar c)
{
  switch (c) {
  case 0x1F468:
    return (void *) emoji_lookup_node_30;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_97 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_98;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_98 (gunichar c)
{
  switch (c) {
  case 0x1F468:
    return (void *) emoji_lookup_node_32;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_99 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_100;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_100 (gunichar c)
{
  switch (c) {
  case 0x1F468:
    return (void *) emoji_lookup_node_34;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_101 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_102;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_102 (gunichar c)
{
  switch (c) {
  case 0x1F469:
    return (void *) emoji_lookup_node_26;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_103 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_104;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_104 (gunichar c)
{
  switch (c) {
  case 0x1F469:
    return (void *) emoji_lookup_node_28;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_105 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_106;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_106 (gunichar c)
{
  switch (c) {
  case 0x1F469:
    return (void *) emoji_lookup_node_30;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_107 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_108;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_108 (gunichar c)
{
  switch (c) {
  case 0x1F469:
    return (void *) emoji_lookup_node_32;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_109 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_110;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_110 (gunichar c)
{
  switch (c) {
  case 0x1F469:
    return (void *) emoji_lookup_node_34;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_111 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_112;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_112 (gunichar c)
{
  switch (c) {
  case 0x1F9D1:
    return (void *) emoji_lookup_node_2;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_113 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_114;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_114 (gunichar c)
{
  switch (c) {
  case 0x1F9D1:
    return (void *) emoji_lookup_node_17;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_115 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_116;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_116 (gunichar c)
{
  switch (c) {
  case 0x1F468 ... 0x1F469 /* 2 */:
    return (void *) emoji_lookup_node_26;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_117 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_118;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_118 (gunichar c)
{
  switch (c) {
  case 0x1F468 ... 0x1F469 /* 2 */:
    return (void *) emoji_lookup_node_28;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_119 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_120;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_120 (gunichar c)
{
  switch (c) {
  case 0x1F468 ... 0x1F469 /* 2 */:
    return (void *) emoji_lookup_node_30;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_121 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_122;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_122 (gunichar c)
{
  switch (c) {
  case 0x1F468 ... 0x1F469 /* 2 */:
    return (void *) emoji_lookup_node_32;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_123 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_124;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_124 (gunichar c)
{
  switch (c) {
  case 0x1F468 ... 0x1F469 /* 2 */:
    return (void *) emoji_lookup_node_34;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_125 (gunichar c)
{
  switch (c) {
  case 0xFE0F:
    return (void *) emoji_lookup_node_126;
  case 0x200D:
    return (void *) emoji_lookup_node_127;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_126 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_127;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_127 (gunichar c)
{
  switch (c) {
  case 0x1F48B:
    return (void *) emoji_lookup_node_81;
  case 0x1F9D1:
    return (void *) emoji_lookup_node_26;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_128 (gunichar c)
{
  switch (c) {
  case 0xFE0F:
    return (void *) emoji_lookup_node_129;
  case 0x200D:
    return (void *) emoji_lookup_node_130;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_129 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_130;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_130 (gunichar c)
{
  switch (c) {
  case 0x1F48B:
    return (void *) emoji_lookup_node_83;
  case 0x1F9D1:
    return (void *) emoji_lookup_node_28;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_131 (gunichar c)
{
  switch (c) {
  case 0xFE0F:
    return (void *) emoji_lookup_node_132;
  case 0x200D:
    return (void *) emoji_lookup_node_133;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_132 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_133;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_133 (gunichar c)
{
  switch (c) {
  case 0x1F48B:
    return (void *) emoji_lookup_node_85;
  case 0x1F9D1:
    return (void *) emoji_lookup_node_30;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_134 (gunichar c)
{
  switch (c) {
  case 0xFE0F:
    return (void *) emoji_lookup_node_135;
  case 0x200D:
    return (void *) emoji_lookup_node_136;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_135 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_136;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_136 (gunichar c)
{
  switch (c) {
  case 0x1F48B:
    return (void *) emoji_lookup_node_87;
  case 0x1F9D1:
    return (void *) emoji_lookup_node_32;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_137 (gunichar c)
{
  switch (c) {
  case 0xFE0F:
    return (void *) emoji_lookup_node_138;
  case 0x200D:
    return (void *) emoji_lookup_node_139;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_138 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_139;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_139 (gunichar c)
{
  switch (c) {
  case 0x1F48B:
    return (void *) emoji_lookup_node_89;
  case 0x1F9D1:
    return (void *) emoji_lookup_node_34;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_140 (gunichar c)
{
  switch (c) {
  case 0xFE0F:
    return (void *) emoji_lookup_node_141;
  case 0x200D:
    return (void *) emoji_lookup_node_142;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_141 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_142;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_142 (gunichar c)
{
  switch (c) {
  case 0x1F48B:
    return (void *) emoji_lookup_node_143;
  case 0x1F468 ... 0x1F469 /* 2 */:
    return (void *) emoji_lookup_node_2;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_143 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_144;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_144 (gunichar c)
{
  switch (c) {
  case 0x1F468 ... 0x1F469 /* 2 */:
    return (void *) emoji_lookup_node_2;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_145 (gunichar c)
{
  switch (c) {
  case 0xFE0F:
    return (void *) emoji_lookup_node_146;
  case 0x200D:
    return (void *) emoji_lookup_node_147;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_146 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_147;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_147 (gunichar c)
{
  switch (c) {
  case 0x1F48B:
    return (void *) emoji_lookup_node_148;
  case 0x1F468 ... 0x1F469 /* 2 */:
    return (void *) emoji_lookup_node_17;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_148 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_149;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_149 (gunichar c)
{
  switch (c) {
  case 0x1F468 ... 0x1F469 /* 2 */:
    return (void *) emoji_lookup_node_17;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_150 (gunichar c)
{
  switch (c) {
  case 0xFE0F:
    return (void *) emoji_lookup_node_151;
  case 0x200D:
    return (void *) emoji_lookup_node_152;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_151 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_152;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_152 (gunichar c)
{
  switch (c) {
  case 0x1F48B:
    return (void *) emoji_lookup_node_153;
  case 0x1F468:
    return (void *) emoji_lookup_node_2;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_153 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_154;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_154 (gunichar c)
{
  switch (c) {
  case 0x1F468:
    return (void *) emoji_lookup_node_2;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_155 (gunichar c)
{
  switch (c) {
  case 0xFE0F:
    return (void *) emoji_lookup_node_156;
  case 0x200D:
    return (void *) emoji_lookup_node_157;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_156 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_157;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_157 (gunichar c)
{
  switch (c) {
  case 0x1F48B:
    return (void *) emoji_lookup_node_158;
  case 0x1F468:
    return (void *) emoji_lookup_node_17;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_158 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_159;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_159 (gunichar c)
{
  switch (c) {
  case 0x1F468:
    return (void *) emoji_lookup_node_17;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_160 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_161;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_161 (gunichar c)
{
  switch (c) {
  case 0x1F466:
    return (void *) emoji_lookup_node_162;
  case 0x1F467:
    return (void *) emoji_lookup_node_163;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_162 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_165;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_163 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_164;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_164 (gunichar c)
{
  switch (c) {
  case 0x1F466 ... 0x1F467 /* 2 */:
    return (void *) emoji_lookup_node_2;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_165 (gunichar c)
{
  switch (c) {
  case 0x1F466:
    return (void *) emoji_lookup_node_2;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_166 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_167;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_167 (gunichar c)
{
  switch (c) {
  case 0x1F9D2:
    return (void *) emoji_lookup_node_168;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_168 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_169;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_169 (gunichar c)
{
  switch (c) {
  case 0x1F9D2:
    return (void *) emoji_lookup_node_2;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_170 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_171;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_171 (gunichar c)
{
  switch (c) {
  case 0x1F9BA:
    return (void *) emoji_lookup_node_2;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_172 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_173;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_173 (gunichar c)
{
  switch (c) {
  case 0x2B1B:
    return (void *) emoji_lookup_node_2;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_174 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_175;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_175 (gunichar c)
{
  switch (c) {
  case 0x2744:
    return (void *) emoji_lookup_node_1;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_176 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_177;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_177 (gunichar c)
{
  switch (c) {
  case 0x2B1B:
  case 0x1F525:
    return (void *) emoji_lookup_node_2;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_178 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_179;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_179 (gunichar c)
{
  switch (c) {
  case 0x1F7E9:
    return (void *) emoji_lookup_node_2;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_180 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_181;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_181 (gunichar c)
{
  switch (c) {
  case 0x1F7EB:
    return (void *) emoji_lookup_node_2;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_182 (gunichar c)
{
  switch (c) {
  case 0xFE0F:
    return (void *) emoji_lookup_node_183;
  case 0x200D:
    return (void *) emoji_lookup_node_184;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_183 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_184;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_184 (gunichar c)
{
  switch (c) {
  case 0x1F4A5:
    return (void *) emoji_lookup_node_2;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_185 (gunichar c)
{
  switch (c) {
  case 0xFE0F:
    return (void *) emoji_lookup_node_186;
  case 0x20E3:
    return (void *) emoji_lookup_node_2;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_186 (gunichar c)
{
  switch (c) {
  case 0x20E3:
    return (void *) emoji_lookup_node_2;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_187 (gunichar c)
{
  switch (c) {
  case 0xFE0F:
    return (void *) emoji_lookup_node_188;
  case 0x200D:
    return (void *) emoji_lookup_node_189;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_188 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_189;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_189 (gunichar c)
{
  switch (c) {
  case 0x1F308:
    return (void *) emoji_lookup_node_2;
  case 0x26A7:
    return (void *) emoji_lookup_node_1;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_190 (gunichar c)
{
  switch (c) {
  case 0x200D:
    return (void *) emoji_lookup_node_191;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_191 (gunichar c)
{
  switch (c) {
  case 0x2620:
    return (void *) emoji_lookup_node_1;
  default:
    return NULL;
  }
}

static void *emoji_lookup_node_192 (gunichar c)
{
  switch (c) {
  case 0x1F1E6 ... 0x1F1FF /* 26 */:
    return (void *) emoji_lookup_node_2;
  default:
    return NULL;
  }
}

/* Whather the character is potentially the second or later character of an emoji sequence */
bool is_emoji_combining(gunichar c)
{
  switch (c) {
  case 0x200D:
  case 0x20E3:
  case 0x2194 ... 0x2195:
  case 0x2620:
  case 0x2640:
  case 0x2642:
  case 0x2695 ... 0x2696:
  case 0x26A7:
  case 0x2708:
  case 0x2744:
  case 0x2764:
  case 0x27A1:
  case 0x2B1B:
  case 0xFE0F:
  case 0x1F1E6 ... 0x1F1FF:
  case 0x1F308:
  case 0x1F32B:
  case 0x1F33E:
  case 0x1F373:
  case 0x1F37C:
  case 0x1F384:
  case 0x1F393:
  case 0x1F3A4:
  case 0x1F3A8:
  case 0x1F3EB:
  case 0x1F3ED:
  case 0x1F3FB ... 0x1F3FF:
  case 0x1F430:
  case 0x1F466 ... 0x1F469:
  case 0x1F48B:
  case 0x1F4A5:
  case 0x1F4A8:
  case 0x1F4AB:
  case 0x1F4BB ... 0x1F4BC:
  case 0x1F525:
  case 0x1F527:
  case 0x1F52C:
  case 0x1F5E8:
  case 0x1F680:
  case 0x1F692:
  case 0x1F7E9:
  case 0x1F7EB:
  case 0x1F91D:
  case 0x1F9AF ... 0x1F9B3:
  case 0x1F9BA:
  case 0x1F9BC ... 0x1F9BD:
  case 0x1F9D1 ... 0x1F9D2:
  case 0x1FA70:
  case 0x1FA79:
  case 0x1FAEF:
  case 0x1FAF2:
    return true;
  default:
    return false;
  }
}

/* A hopefully slightly faster variant for when we already know that the character is narrow */
bool is_single_width_emoji_combining(gunichar c)
{
  switch (c) {
  case 0x2194 ... 0x2195:
  case 0x2620:
  case 0x2640:
  case 0x2642:
  case 0x2695 ... 0x2696:
  case 0x26A7:
  case 0x2708:
  case 0x2744:
  case 0x2764:
  case 0x27A1:
  case 0x1F1E6 ... 0x1F1FF:
  case 0x1F32B:
  case 0x1F5E8:
  case 0x1FAEF:
    return true;
  default:
    return false;
  }
}

