#!/bin/sh
#
#  Operating system commands.
#
if [ "$#" -eq 0 ] ; then
	echo usage: `basename $0` 'command [...]'
	echo commands:
	echo "	0 'title'	change icon name and window title"
	echo "	1 'title'	change icon name"
	echo "	2 'title'	change window title"
	echo "	12 'color'	change cursor color"
	exit
fi
args=
for arg in $@ ; do
	if [ "$args" = "" ] ; then
		args="$arg"
	else
		args="$args;$arg"
	fi
done
printf "]"${args}
