const struct { gchar code[2]; guchar handler; }
vte_sequence_handlers_two[] = {
  {"!1", vte_sequence_handler_complain_key_index},
  {"!2", vte_sequence_handler_complain_key_index},
  {"!3", vte_sequence_handler_complain_key_index},
  {"#1", vte_sequence_handler_complain_key_index},
  {"#2", vte_sequence_handler_complain_key_index},
  {"#3", vte_sequence_handler_complain_key_index},
  {"#4", vte_sequence_handler_complain_key_index},
  {"%1", vte_sequence_handler_complain_key_index},
  {"%2", vte_sequence_handler_complain_key_index},
  {"%3", vte_sequence_handler_complain_key_index},
  {"%4", vte_sequence_handler_complain_key_index},
  {"%5", vte_sequence_handler_complain_key_index},
  {"%6", vte_sequence_handler_complain_key_index},
  {"%7", vte_sequence_handler_complain_key_index},
  {"%8", vte_sequence_handler_complain_key_index},
  {"%9", vte_sequence_handler_complain_key_index},
  {"%a", vte_sequence_handler_complain_key_index},
  {"%b", vte_sequence_handler_complain_key_index},
  {"%c", vte_sequence_handler_complain_key_index},
  {"%d", vte_sequence_handler_complain_key_index},
  {"%e", vte_sequence_handler_complain_key_index},
  {"%f", vte_sequence_handler_complain_key_index},
  {"%g", vte_sequence_handler_complain_key_index},
  {"%h", vte_sequence_handler_complain_key_index},
  {"%i", vte_sequence_handler_complain_key_index},
  {"%j", vte_sequence_handler_complain_key_index},
  {"&0", vte_sequence_handler_complain_key_index},
  {"&1", vte_sequence_handler_complain_key_index},
  {"&2", vte_sequence_handler_complain_key_index},
  {"&3", vte_sequence_handler_complain_key_index},
  {"&4", vte_sequence_handler_complain_key_index},
  {"&5", vte_sequence_handler_complain_key_index},
  {"&6", vte_sequence_handler_complain_key_index},
  {"&7", vte_sequence_handler_complain_key_index},
  {"&8", vte_sequence_handler_complain_key_index},
  {"&9", vte_sequence_handler_complain_key_index},
  {"*0", vte_sequence_handler_complain_key_index},
  {"*1", vte_sequence_handler_complain_key_index},
  {"*2", vte_sequence_handler_complain_key_index},
  {"*3", vte_sequence_handler_complain_key_index},
  {"*4", vte_sequence_handler_complain_key_index},
  {"*5", vte_sequence_handler_complain_key_index},
  {"*6", vte_sequence_handler_complain_key_index},
  {"*7", vte_sequence_handler_complain_key_index},
  {"*8", vte_sequence_handler_complain_key_index},
  {"*9", vte_sequence_handler_complain_key_index},
  {"@0", vte_sequence_handler_complain_key_index},
  {"@1", vte_sequence_handler_complain_key_index},
  {"@2", vte_sequence_handler_complain_key_index},
  {"@3", vte_sequence_handler_complain_key_index},
  {"@4", vte_sequence_handler_complain_key_index},
  {"@5", vte_sequence_handler_complain_key_index},
  {"@6", vte_sequence_handler_complain_key_index},
  {"@7", vte_sequence_handler_complain_key_index},
  {"@8", vte_sequence_handler_complain_key_index},
  {"@9", vte_sequence_handler_complain_key_index},
  {"AL", vte_sequence_handler_AL_index},
  {"DC", vte_sequence_handler_DC_index},
  {"DL", vte_sequence_handler_DL_index},
  {"DO", vte_sequence_handler_DO_index},
  {"F1", vte_sequence_handler_complain_key_index},
  {"F2", vte_sequence_handler_complain_key_index},
  {"F3", vte_sequence_handler_complain_key_index},
  {"F4", vte_sequence_handler_complain_key_index},
  {"F5", vte_sequence_handler_complain_key_index},
  {"F6", vte_sequence_handler_complain_key_index},
  {"F7", vte_sequence_handler_complain_key_index},
  {"F8", vte_sequence_handler_complain_key_index},
  {"F9", vte_sequence_handler_complain_key_index},
  {"FA", vte_sequence_handler_complain_key_index},
  {"FB", vte_sequence_handler_complain_key_index},
  {"FC", vte_sequence_handler_complain_key_index},
  {"FD", vte_sequence_handler_complain_key_index},
  {"FE", vte_sequence_handler_complain_key_index},
  {"FF", vte_sequence_handler_complain_key_index},
  {"FG", vte_sequence_handler_complain_key_index},
  {"FH", vte_sequence_handler_complain_key_index},
  {"FI", vte_sequence_handler_complain_key_index},
  {"FJ", vte_sequence_handler_complain_key_index},
  {"FK", vte_sequence_handler_complain_key_index},
  {"FL", vte_sequence_handler_complain_key_index},
  {"FM", vte_sequence_handler_complain_key_index},
  {"FN", vte_sequence_handler_complain_key_index},
  {"FO", vte_sequence_handler_complain_key_index},
  {"FP", vte_sequence_handler_complain_key_index},
  {"FQ", vte_sequence_handler_complain_key_index},
  {"FR", vte_sequence_handler_complain_key_index},
  {"FS", vte_sequence_handler_complain_key_index},
  {"FT", vte_sequence_handler_complain_key_index},
  {"FU", vte_sequence_handler_complain_key_index},
  {"FV", vte_sequence_handler_complain_key_index},
  {"FW", vte_sequence_handler_complain_key_index},
  {"FX", vte_sequence_handler_complain_key_index},
  {"FY", vte_sequence_handler_complain_key_index},
  {"FZ", vte_sequence_handler_complain_key_index},
  {"Fa", vte_sequence_handler_complain_key_index},
  {"Fb", vte_sequence_handler_complain_key_index},
  {"Fc", vte_sequence_handler_complain_key_index},
  {"Fd", vte_sequence_handler_complain_key_index},
  {"Fe", vte_sequence_handler_complain_key_index},
  {"Ff", vte_sequence_handler_complain_key_index},
  {"Fg", vte_sequence_handler_complain_key_index},
  {"Fh", vte_sequence_handler_complain_key_index},
  {"Fi", vte_sequence_handler_complain_key_index},
  {"Fj", vte_sequence_handler_complain_key_index},
  {"Fk", vte_sequence_handler_complain_key_index},
  {"Fl", vte_sequence_handler_complain_key_index},
  {"Fm", vte_sequence_handler_complain_key_index},
  {"Fn", vte_sequence_handler_complain_key_index},
  {"Fo", vte_sequence_handler_complain_key_index},
  {"Fp", vte_sequence_handler_complain_key_index},
  {"Fq", vte_sequence_handler_complain_key_index},
  {"Fr", vte_sequence_handler_complain_key_index},
  {"IC", vte_sequence_handler_IC_index},
  {"K1", vte_sequence_handler_complain_key_index},
  {"K2", vte_sequence_handler_complain_key_index},
  {"K3", vte_sequence_handler_complain_key_index},
  {"K4", vte_sequence_handler_complain_key_index},
  {"K5", vte_sequence_handler_complain_key_index},
  {"LE", vte_sequence_handler_LE_index},
  {"LF", 0},
  {"LO", 0},
  {"MC", 0},
  {"ML", 0},
  {"MR", 0},
  {"RA", 0},
  {"RF", 0},
  {"RI", vte_sequence_handler_RI_index},
  {"RX", 0},
  {"SA", 0},
  {"SF", vte_sequence_handler_SF_index},
  {"SR", vte_sequence_handler_SR_index},
  {"SX", 0},
  {"UP", vte_sequence_handler_UP_index},
  {"XF", 0},
  {"ae", vte_sequence_handler_ae_index},
  {"al", vte_sequence_handler_al_index},
  {"as", vte_sequence_handler_as_index},
  {"bc", vte_sequence_handler_le_index},
  {"bl", vte_sequence_handler_bl_index},
  {"bt", vte_sequence_handler_bt_index},
  {"cS", vte_sequence_handler_cS_index},
  {"cb", vte_sequence_handler_cb_index},
  {"cc", vte_sequence_handler_noop_index},
  {"cd", vte_sequence_handler_cd_index},
  {"ce", vte_sequence_handler_ce_index},
  {"ch", vte_sequence_handler_ch_index},
  {"cl", vte_sequence_handler_cl_index},
  {"cm", vte_sequence_handler_cm_index},
  {"cr", vte_sequence_handler_cr_index},
  {"cs", vte_sequence_handler_cs_index},
  {"ct", vte_sequence_handler_ct_index},
  {"cv", vte_sequence_handler_cv_index},
  {"dc", vte_sequence_handler_dc_index},
  {"dl", vte_sequence_handler_dl_index},
  {"dm", vte_sequence_handler_noop_index},
  {"do", vte_sequence_handler_do_index},
  {"ds", 0},
  {"eA", vte_sequence_handler_eA_index},
  {"ec", vte_sequence_handler_ec_index},
  {"ed", vte_sequence_handler_noop_index},
  {"ei", vte_sequence_handler_ei_index},
  {"ff", vte_sequence_handler_noop_index},
  {"fs", vte_sequence_handler_fs_index},
  {"hd", 0},
  {"ho", vte_sequence_handler_ho_index},
  {"hu", 0},
  {"i1", 0},
  {"i3", 0},
  {"iP", 0},
  {"ic", vte_sequence_handler_ic_index},
  {"if", 0},
  {"im", vte_sequence_handler_im_index},
  {"ip", 0},
  {"is", 0},
  {"k0", vte_sequence_handler_complain_key_index},
  {"k1", vte_sequence_handler_complain_key_index},
  {"k2", vte_sequence_handler_complain_key_index},
  {"k3", vte_sequence_handler_complain_key_index},
  {"k4", vte_sequence_handler_complain_key_index},
  {"k5", vte_sequence_handler_complain_key_index},
  {"k6", vte_sequence_handler_complain_key_index},
  {"k7", vte_sequence_handler_complain_key_index},
  {"k8", vte_sequence_handler_complain_key_index},
  {"k9", vte_sequence_handler_complain_key_index},
  {"k;", vte_sequence_handler_complain_key_index},
  {"kA", vte_sequence_handler_complain_key_index},
  {"kB", vte_sequence_handler_complain_key_index},
  {"kC", vte_sequence_handler_complain_key_index},
  {"kD", vte_sequence_handler_complain_key_index},
  {"kE", vte_sequence_handler_complain_key_index},
  {"kF", vte_sequence_handler_complain_key_index},
  {"kH", vte_sequence_handler_complain_key_index},
  {"kI", vte_sequence_handler_complain_key_index},
  {"kL", vte_sequence_handler_complain_key_index},
  {"kM", vte_sequence_handler_complain_key_index},
  {"kN", vte_sequence_handler_complain_key_index},
  {"kP", vte_sequence_handler_complain_key_index},
  {"kR", vte_sequence_handler_complain_key_index},
  {"kS", vte_sequence_handler_complain_key_index},
  {"kT", vte_sequence_handler_complain_key_index},
  {"ka", vte_sequence_handler_complain_key_index},
  {"kb", vte_sequence_handler_kb_index},
  {"kd", vte_sequence_handler_complain_key_index},
  {"ke", vte_sequence_handler_ke_index},
  {"kh", vte_sequence_handler_complain_key_index},
  {"kl", vte_sequence_handler_complain_key_index},
  {"kr", vte_sequence_handler_complain_key_index},
  {"ks", vte_sequence_handler_ks_index},
  {"kt", vte_sequence_handler_complain_key_index},
  {"ku", vte_sequence_handler_complain_key_index},
  {"l0", 0},
  {"l1", 0},
  {"l2", 0},
  {"l3", 0},
  {"l4", 0},
  {"l5", 0},
  {"l6", 0},
  {"l7", 0},
  {"l8", 0},
  {"l9", 0},
  {"la", 0},
  {"le", vte_sequence_handler_le_index},
  {"ll", vte_sequence_handler_ll_index},
  {"mb", vte_sequence_handler_mb_index},
  {"md", vte_sequence_handler_md_index},
  {"me", vte_sequence_handler_me_index},
  {"mh", vte_sequence_handler_mh_index},
  {"mk", vte_sequence_handler_mk_index},
  {"mm", 0},
  {"mo", 0},
  {"mp", vte_sequence_handler_mp_index},
  {"mr", vte_sequence_handler_mr_index},
  {"nd", vte_sequence_handler_nd_index},
  {"nw", vte_sequence_handler_nw_index},
  {"pO", 0},
  {"pc", 0},
  {"pf", 0},
  {"pk", 0},
  {"pl", 0},
  {"pn", 0},
  {"po", 0},
  {"ps", 0},
  {"px", 0},
  {"r1", 0},
  {"r2", 0},
  {"r3", 0},
  {"rP", 0},
  {"rc", vte_sequence_handler_rc_index},
  {"rf", 0},
  {"rp", 0},
  {"rs", 0},
  {"sa", 0},
  {"sc", vte_sequence_handler_sc_index},
  {"se", vte_sequence_handler_se_index},
  {"sf", vte_sequence_handler_sf_index},
  {"so", vte_sequence_handler_so_index},
  {"sr", vte_sequence_handler_sr_index},
  {"st", vte_sequence_handler_st_index},
  {"ta", vte_sequence_handler_ta_index},
  {"te", vte_sequence_handler_noop_index},
  {"ti", vte_sequence_handler_noop_index},
  {"ts", vte_sequence_handler_ts_index},
  {"uc", vte_sequence_handler_uc_index},
  {"ue", vte_sequence_handler_ue_index},
  {"up", vte_sequence_handler_up_index},
  {"us", vte_sequence_handler_us_index},
  {"vb", vte_sequence_handler_vb_index},
  {"ve", vte_sequence_handler_ve_index},
  {"vi", vte_sequence_handler_vi_index},
  {"vs", vte_sequence_handler_vs_index},
  {"wi", 0},
};

const struct { guchar len; guchar handler; gchar code[37+1]; }
vte_sequence_handlers_others[] = {
  {4, 0, "..rp"},
  {4, 0, "..sa"},
  {5, vte_sequence_handler_index_index, "index"},
  {6, vte_sequence_handler_decset_index, "decset"},
  {6, 0, "repeat"},
  {7, vte_sequence_handler_st_index, "tab-set"},
  {8, vte_sequence_handler_decreset_index, "decreset"},
  {8, vte_sequence_handler_set_mode_index, "set-mode"},
  {9, vte_sequence_handler_UP_index, "cursor-up"},
  {9, vte_sequence_handler_form_feed_index, "form-feed"},
  {9, vte_sequence_handler_next_line_index, "next-line"},
  {9, vte_sequence_handler_save_mode_index, "save-mode"},
  {9, vte_sequence_handler_scroll_up_index, "scroll-up"},
  {9, vte_sequence_handler_tab_clear_index, "tab-clear"},
  {10, vte_sequence_handler_full_reset_index, "full-reset"},
  {10, 0, "media-copy"},
  {10, vte_sequence_handler_reset_mode_index, "reset-mode"},
  {10, vte_sequence_handler_soft_reset_index, "soft-reset"},
  {11, vte_sequence_handler_DO_index, "cursor-down"},
  {11, 0, "memory-lock"},
  {11, vte_sequence_handler_sc_index, "save-cursor"},
  {11, vte_sequence_handler_scroll_down_index, "scroll-down"},
  {12, 0, "change-color"},
  {12, vte_sequence_handler_delete_lines_index, "delete-lines"},
  {12, 0, "double-width"},
  {12, vte_sequence_handler_insert_lines_index, "insert-lines"},
  {12, vte_sequence_handler_restore_mode_index, "restore-mode"},
  {12, 0, "single-width"},
  {12, vte_sequence_handler_vertical_tab_index, "vertical-tab"},
  {13, vte_sequence_handler_erase_in_line_index, "erase-in-line"},
  {13, 0, "memory-unlock"},
  {13, vte_sequence_handler_normal_keypad_index, "normal-keypad"},
  {13, vte_sequence_handler_reverse_index_index, "reverse-index"},
  {14, 0, "7-bit-controls"},
  {14, 0, "8-bit-controls"},
  {14, 0, "change-logfile"},
  {14, vte_sequence_handler_RI_index, "cursor-forward"},
  {14, 0, "dec-media-copy"},
  {14, vte_sequence_handler_rc_index, "restore-cursor"},
  {14, vte_sequence_handler_set_icon_title_index, "set-icon-title"},
  {15, vte_sequence_handler_bt_index, "cursor-back-tab"},
  {15, vte_sequence_handler_LE_index, "cursor-backward"},
  {15, vte_sequence_handler_cursor_position_index, "cursor-position"},
  {15, 0, "single-shift-g2"},
  {15, 0, "single-shift-g3"},
  {16, 0, "change-font-name"},
  {16, vte_sequence_handler_cursor_next_line_index, "cursor-next-line"},
  {16, vte_sequence_handler_erase_characters_index, "erase-characters"},
  {16, vte_sequence_handler_erase_in_display_index, "erase-in-display"},
  {16, vte_sequence_handler_set_window_title_index, "set-window-title"},
  {17, vte_sequence_handler_cursor_lower_left_index, "cursor-lower-left"},
  {17, vte_sequence_handler_DC_index, "delete-characters"},
  {18, vte_sequence_handler_application_keypad_index, "application-keypad"},
  {18, 0, "change-font-number"},
  {18, vte_sequence_handler_return_terminal_id_index, "return-terminal-id"},
  {19, 0, "end-of-guarded-area"},
  {19, vte_sequence_handler_utf_8_charset_index, "utf-8-character-set"},
  {19, vte_sequence_handler_window_manipulation_index, "window-manipulation"},
  {20, 0, "change-cursor-colors"},
  {20, vte_sequence_handler_character_attributes_index, "character-attributes"},
  {20, vte_sequence_handler_device_status_report_index, "device-status-report"},
  {20, vte_sequence_handler_set_scrolling_region_index, "set-scrolling-region"},
  {20, 0, "set-text-property-21"},
  {20, 0, "set-text-property-2L"},
  {21, vte_sequence_handler_cursor_preceding_line_index, "cursor-preceding-line"},
  {21, 0, "device-control-string"},
  {21, vte_sequence_handler_screen_alignment_test_index, "screen-alignment-test"},
  {21, 0, "select-locator-events"},
  {21, 0, "set-conformance-level"},
  {21, 0, "start-of-guarded-area"},
  {22, 0, "double-height-top-half"},
  {22, vte_sequence_handler_line_position_absolute_index, "line-position-absolute"},
  {22, vte_sequence_handler_return_terminal_status_index, "return-terminal-status"},
  {23, 0, "change-highlight-colors"},
  {23, 0, "enable-filter-rectangle"},
  {23, vte_sequence_handler_insert_blank_characters_index, "insert-blank-characters"},
  {23, 0, "invoke-g2-character-set"},
  {23, 0, "invoke-g3-character-set"},
  {23, vte_sequence_handler_local_charset_index, "iso8859-1-character-set"},
  {23, 0, "selective-erase-in-line"},
  {24, 0, "ansi-conformance-level-1"},
  {24, 0, "ansi-conformance-level-2"},
  {24, 0, "ansi-conformance-level-3"},
  {24, 0, "change-background-colors"},
  {24, 0, "change-foreground-colors"},
  {24, vte_sequence_handler_dec_device_status_report_index, "dec-device-status-report"},
  {24, 0, "enable-locator-reporting"},
  {24, 0, "request-locator-position"},
  {25, vte_sequence_handler_cursor_character_absolute_index, "cursor-character-absolute"},
  {25, vte_sequence_handler_ta_index, "cursor-forward-tabulation"},
  {25, 0, "double-height-bottom-half"},
  {25, vte_sequence_handler_set_icon_and_window_title_index, "set-icon-and-window-title"},
  {26, 0, "selective-erase-in-display"},
  {27, vte_sequence_handler_character_position_absolute_index, "character-position-absolute"},
  {27, vte_sequence_handler_request_terminal_parameters_index, "request-terminal-parameters"},
  {27, 0, "select-character-protection"},
  {28, 0, "change-tek-background-colors"},
  {28, 0, "change-tek-foreground-colors"},
  {29, 0, "invoke-g1-character-set-as-gr"},
  {29, 0, "invoke-g2-character-set-as-gr"},
  {29, 0, "invoke-g3-character-set-as-gr"},
  {30, 0, "initiate-hilite-mouse-tracking"},
  {30, vte_sequence_handler_send_primary_device_attributes_index, "send-primary-device-attributes"},
  {31, vte_sequence_handler_noop_index, "linux-console-cursor-attributes"},
  {32, vte_sequence_handler_horizontal_and_vertical_position_index, "horizontal-and-vertical-position"},
  {32, vte_sequence_handler_send_secondary_device_attributes_index, "send-secondary-device-attributes"},
  {37, 0, "change-mouse-cursor-background-colors"},
  {37, 0, "change-mouse-cursor-foreground-colors"},
};

